name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cicdsample
          path: build/libs/*.jar

      # 추가
      - name: Make zip file #1
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials #2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3 #3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://dw-bucket-test1234/$GITHUB_SHA.zip


      - name: Code Deploy #4
#       basion server deploy
#        run: aws deploy create-deployment --application-name dw-codedeploy-app --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name dw-deploy-group --s3-location bucket=dw-bucket-test1234,bundleType=zip,key=$GITHUB_SHA.zip

#       auto scaling group deploy
        run: aws deploy create-deployment --application-name dw-codedeploy-app --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name dw-auto-group --s3-location bucket=dw-bucket-test1234,bundleType=zip,key=$GITHUB_SHA.zip

